### ISSUE TITLE
Discrepancies With Package Registration

### ISSUE THREAD

**Issue by ThuleanInsight** [fipelle/MessyTimeSeries.jl#17]
Performing the usual ```]add TSAnalysis``` has an issue. The first thing I tried was 

```julia
Y = Array(tdata)
d = 1;
p = 0;
q = 5;
arima_settings = ARIMASettings(Y, d, p, q)
```

Copied from the notes on the homepage. This resulted in the error 
```julia
ERROR: LoadError: UndefVarError: ARIMASettings not defined
``` 

I checked the source files on the main branch, which revealed the exports as follows 

```julia
module TSAnalysis

    # Libraries
    using Dates, Distributed, Logging;
    using LinearAlgebra, Distributions, Statistics;

    # Custom dependencies
    const local_path = dirname(@__FILE__);
    include("$local_path/types.jl");
    include("$local_path/methods.jl");
    include("$local_path/kalman.jl");
    include("$local_path/subsampling.jl");
    #include("$local_path/uc_models.jl");

    # Export types
    export JVector, JArray, IntVector, IntMatrix, IntArray, FloatVector, FloatMatrix, FloatArray, SymMatrix, DiagMatrix,
           KalmanSettings, ImmutableKalmanSettings, MutableKalmanSettings, KalmanStatus,
           ARIMASettings, VARIMASettings;
```
We can see ARIMASettings is clearly exported here. I checked the actual file on disk, though, and get the following:

```julia
module TSAnalysis

    # Libraries
    using Distributed;
    using Dates, Logging;
    using LinearAlgebra, Distributions, Statistics;

    # Custom dependencies
    const local_path = dirname(@__FILE__);
    include("$local_path/types.jl");
    include("$local_path/methods.jl");
    include("$local_path/kalman.jl");

    # Export
    export JVector, JArray, KalmanSettings, ImmutableKalmanSettings, MutableKalmanSettings, KalmanStatus;
    export mean_skipmissing, std_skipmissing, is_vector_in_matrix, demean, lag, companion_form, ext_companion_form;
    export kfilter!, kforecast, ksmoother;
end
```
I do not have an explanation for the substantial difference here, but the package is currently not usable via the typical method because so many of the exports are lacking.

**Comment by fipelle** [comment]
Hi there, 

The registered version is not what you are seeing in the master and dev branches. I am currently in the process of moving the estimation functions into a separate package and thus I have temporarily commented them out. This child package will be out by the end of summer and it will include a few extra models.

Right now, there are a few options that you can follow:

1. use the latest registered version of TSAnalysis and pin down the version of Optim required to install it;
2. use a previous registered version of TSAnalysis;
3. download the latest registered version of TSAnalysis from [here](https://github.com/fipelle/TSAnalysis.jl/releases/tag/0.1.4) and use it locally with the most up-to-date dependencies;
4. use the latest unregistered development version of TSAnalysis installing it via ```]add TSAnalysis#dev```.

Please note that for options 1 and 2 all you need to do is running ```]add TSAnalysis``` after having decided what to do with Optim. Also, option 4 does not include the estimation functions for the reasons described above.

If you need to estimate VARIMA models right now I would personally use option 3. Option 4 is best if you only need to use the Kaman filter and smoother since it includes much more stable and efficient implementations.

**Comment by ThuleanInsight** [comment]
A clear answer, thank you. You may want an abbreviated explanation as a note at the top of the Readme here.

**Comment by fipelle** [comment]
I have pinned it for now. I think it should be enough for now.

**Comment by fipelle** [comment]
This has been fixed. Please note that TSAnalysis.jl is now called MessyTimeSeries.jl. The model estimation and validation is addressed in MessyTimeSeriesOptim.jl. The documentation will be released in the following weeks. For now, the docstrings and reference papers ([preprint 1](https://arxiv.org/abs/2002.04697) and [preprint 2](https://arxiv.org/abs/2111.14000)) should be enough.
